export const products = [

    {
        id: '2',
        title: 'MacBook Air M1 2020',
        price: 35000,
        originalPrice: 45000,
        imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Good',
        seller: 'Engineering Graduate',
        posted: '1 week ago',
        likes: 56,
        university: 'Addis Ababa Science and Technology',
        rating: 4.5,
        delivery: 'Meetup',
        description: '256GB SSD, 8GB RAM. Light scratches on casing but works perfectly.'
    },
    {
        id: '3',
        title: 'Organic Chemistry Textbook',
        price: 55,
        originalPrice: 150,
        imageUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Fair',
        seller: 'Chemistry Student',
        posted: '3 days ago',
        likes: 12,
        university: 'Hawassa University',
        rating: 4.2,
        delivery: 'Shipping available',
        description: 'Some highlighting but all pages intact. Great for CHEM 201.'
    },
    {
        id: '4',
        title: 'Wireless Headphones',
        price: 1200,
        originalPrice: 2500,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Excellent',
        seller: 'Business Student',
        posted: '5 hours ago',
        likes: 32,
        university: 'Jimma University',
        rating: 4.7,
        delivery: 'Campus pickup',
        description: 'Brand new, never used. Original packaging included.'
    },
    {
        id: '5',
        title: 'Graphing Calculator',
        price: 800,
        originalPrice: 1200,
        imageUrl: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Good',
        seller: 'Math Tutor',
        posted: '1 day ago',
        likes: 18,
        university: 'Bahir Dar University',
        rating: 4.3,
        delivery: 'Meetup',
        description: 'TI-84 Plus. Works perfectly with fresh batteries included.'
    },
    {
        id: '6',
        title: 'Bicycle for Campus',
        price: 3500,
        originalPrice: 5000,
        imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Used',
        seller: 'Graduating Senior',
        posted: '2 weeks ago',
        likes: 42,
        university: 'Mekelle University',
        rating: 4.0,
        delivery: 'Pickup only',
        description: 'Good condition mountain bike. Perfect for getting around campus.'
    },
    {
        id: '7',
        title: 'Economic Theory Textbook',
        price: 60,
        originalPrice: 140,
        imageUrl: 'https://images.unsplash.com/photo-1589998059171-988d887df646?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Like New',
        seller: 'Economics Major',
        posted: '6 days ago',
        likes: 15,
        university: 'Addis Ababa University',
        rating: 4.6,
        delivery: 'Campus pickup',
        description: 'No markings or highlights. Essential for ECON 301 course.'
    },
    {
        id: '1',
        title: 'Calculus Textbook - 3rd Edition',
        price: 45,
        originalPrice: 120,
        imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Like New',
        seller: 'Computer Science Senior',
        posted: '2 days ago',
        likes: 24,
        university: 'Addis Ababa University',
        rating: 4.8,
        delivery: 'Campus pickup',
        description: 'Excellent condition with minimal highlighting. Perfect for MATH 101 students.'
    },
    {
        id: '8',
        title: 'Dorm Mini-Fridge',
        price: 2800,
        originalPrice: 4500,
        imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Good',
        seller: 'Senior Student',
        posted: '3 days ago',
        likes: 28,
        university: 'Arba Minch University',
        rating: 4.4,
        delivery: 'Pickup only',
        description: '1.7 cubic feet. Works perfectly. Great for keeping drinks cold.'
    },
    {
        id: '9',
        title: 'Java Programming Book',
        price: 605,
        originalPrice: 160,
        imageUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Fair',
        seller: 'CS Student',
        posted: '1 week ago',
        likes: 21,
        university: 'Addis Ababa Science and Technology',
        rating: 4.1,
        delivery: 'Shipping available',
        description: 'Effective Java 3rd Edition. Some wear but content is perfect.'
    },
    {
        id: '10',
        title: 'Portable Study Desk',
        price: 450,
        originalPrice: 700,
        imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=800&q=80',
        condition: 'Like New',
        seller: 'Medical Student',
        posted: '4 days ago',
        likes: 33,
        university: 'Gondar University',
        rating: 4.9,
        delivery: 'Campus pickup',
        description: 'Foldable laptop desk. Perfect for dorm room studying.'
    }
];


export const message = [
    {
        id: 1,
        text: 'Hey there! Is this textbook still available?',
        sender: 'other',
        time: '10:30 AM',
        isRead: true,
    },
    {
        id: 2,
        text: 'Yes, it is! Are you interested?',
        sender: 'me',
        time: '10:32 AM',
        isRead: true,
    },
    {
        id: 3,
        text: 'Definitely! Could we meet on campus tomorrow?',
        sender: 'other',
        time: '10:33 AM',
        isRead: true,
    },
    {
        id: 4,
        text: 'Sure, how about near the library at 2pm?',
        sender: 'me',
        time: '10:35 AM',
        isRead: true,
    },
    {
        id: 5,
        text: 'Perfect! See you then.',
        sender: 'other',
        time: '10:36 AM',
        isRead: false,
    },
    {
        id: 1,
        text: 'Hey there! Is this textbook still available?',
        sender: 'other',
        time: '10:30 AM',
        isRead: true,
    },
    {
        id: 2,
        text: 'Yes, it is! Are you interested?',
        sender: 'me',
        time: '10:32 AM',
        isRead: true,
    },
    {
        id: 3,
        text: 'Definitely! Could we meet on campus tomorrow?',
        sender: 'other',
        time: '10:33 AM',
        isRead: true,
    },
    {
        id: 4,
        text: 'Sure, how about near the library at 2pm?',
        sender: 'me',
        time: '10:35 AM',
        isRead: true,
    },
    {
        id: 5,
        text: 'Perfect! See you then.',
        sender: 'other',
        time: '10:36 AM',
        isRead: false,
    },
    {
        id: 1,
        text: 'Hey there! Is this textbook still available?',
        sender: 'other',
        time: '10:30 AM',
        isRead: true,
    },
    {
        id: 2,
        text: 'Yes, it is! Are you interested?',
        sender: 'me',
        time: '10:32 AM',
        isRead: true,
    },
    {
        id: 3,
        text: 'Definitely! Could we meet on campus tomorrow?',
        sender: 'other',
        time: '10:33 AM',
        isRead: true,
    },
    {
        id: 4,
        text: 'Sure, how about near the library at 2pm?',
        sender: 'me',
        time: '10:35 AM',
        isRead: true,
    },
    {
        id: 5,
        text: 'Perfect! See you then.',
        sender: 'other',
        time: '10:36 AM',
        isRead: false,
    },
]